(defun %boot-log (msg)
  (ignore-errors
    (with-open-file (f #p"/tmp/cl-tron-mcp-boot.log" :direction :output :if-exists :append :if-does-not-exist :create)
      (write-line (format nil "~a ~a" (get-universal-time) msg) f))))
(%boot-log "0: entered")
(setq *compile-verbose* nil *load-verbose* nil)
(%boot-log "1: setq done")
(push #p"/home/emmanuel/quicklisp/local-projects/cl-tron-mcp/" ql:*local-project-directories*)
(%boot-log "2: push done")
(asdf:compile-system :cl-tron-mcp :force t)
(%boot-log "3: compile done")
(asdf:load-system :cl-tron-mcp)
(%boot-log "4: load done")
(let ((port (parse-integer (with-open-file (f #p"/home/emmanuel/quicklisp/local-projects/cl-tron-mcp/http-port.txt") (read-line f)))))
  (%boot-log (format nil "5: port=~a calling start-server" port))
  (cl-tron-mcp/core:start-server :transport :http :port port))
(%boot-log "6: start-server returned")
#+sbcl (sb-ext:quit 0)
#+ecl (ext:quit 0)
#-(or sbcl ecl) (cl-user::quit 0)
